server:
  port: 3005

spring:
  application:
    name: user-feed

  datasource:
    url: jdbc:postgresql://localhost:5432/user-feed
    username: postgres
    password: SQLPassword

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: EmiJor
    password: emilianojordan13

# URL Auth
security:
  auth-server-url: http://localhost:3000

# URL Orders
orders-server-url: http://localhost:3004