spring:
  application:
    name: StockMaster

  datasource:
    url: jdbc:postgresql://localhost:5432/user-feed
    username: postgres
    password: SQLPassword
    #    initialization-mode: always
#  sql:
#    init:
#      mode: always
#
  jpa:
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create
    show-sql: true
    format-sql: true